host:        127.0.0.1
port:        4000

name:        "Welcome to aurumOS"
markdown:    kramdown
highlighter: rouge

permalink:   /news/:title.html

snow:        0
christmas:   0

plugins:
  - jekyll-redirect-from

collections:
  platforms:
    output: true

defaults:
  - scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

download_mirror: https://github.com/ytmrkm/aurum/releases/download
download_build_date: 2024-07-14
container_url: https://github.com/ytmrkm/aurum-packages/pkgs/container/
